#!/bin/sh
#
# Perform necessary nodex-agent setup steps
# after package is installed.
#

INSTALL_DIR=/opt/nodex-agent
SERVICE_NAME=com.nodex.nodex-agent
HOME_DIR=/Users/nodex/

set -e

# Check if the user and group already exist, if not, create them
if ! id -u nodex >/dev/null 2>&1; then
    echo "Creating dedicated user and group for nodex-agent..."
    dscl . -create /Users/nodex
    dscl . -create /Users/nodex UserShell /usr/bin/false
    dscl . -create /Users/nodex RealName "Nodex Agent"
    dscl . -create /Users/nodex UniqueID "510"
    dscl . -create /Users/nodex PrimaryGroupID 20
    dscl . -create /Users/nodex NFSHomeDirectory $HOME_DIR
    mkdir -p $HOME_DIR
    chown nodex:staff $HOME_DIR
else
    echo "User nodex already exists."
fi

# Ensure the installation directory exists before setting ownership and permissions
if [ ! -d "${INSTALL_DIR}" ]; then
    echo "Creating installation directory ${INSTALL_DIR}..."
    mkdir -p ${INSTALL_DIR}
else
    echo "Installation directory ${INSTALL_DIR} already exists."
fi

# Set ownership and permissions
chown -R root:nodex ${INSTALL_DIR}
chmod -R 700 ${INSTALL_DIR}
mkdir -p ${HOME_DIR}
chown -R nodex:staff ${HOME_DIR}
chmod -R 700 ${HOME_DIR}

# Create a symlink to the agent's binary, handling existing symlink
if [ -L /usr/local/bin/nodex-agent ]; then
    echo "Updating existing symlink for nodex-agent..."
    ln -sf $INSTALL_DIR/bin/nodex-agent /usr/local/bin/nodex-agent
elif [ -e /usr/local/bin/nodex-agent ]; then
    echo "A file already exists at /usr/local/bin/nodex-agent. Removing it to create a symlink..."
    rm /usr/local/bin/nodex-agent
    ln -sf $INSTALL_DIR/bin/nodex-agent /usr/local/bin/nodex-agent
else
    echo "Creating a new symlink for nodex-agent..."
    ln -sf $INSTALL_DIR/bin/nodex-agent /usr/local/bin/nodex-agent
fi

# Load the launchd service
if [ -f "/Library/LaunchDaemons/$SERVICE_NAME.plist" ]; then
    echo "Loading the $SERVICE_NAME service..."
    launchctl load /Library/LaunchDaemons/$SERVICE_NAME.plist
    launchctl enable system/$SERVICE_NAME
else
    echo "[ WARNING ]\tThe launchd service file was not found. Please ensure it is installed correctly."
fi

# Start the service if the configuration file exists
if [ -f "$HOME_DIR/.config/nodex/config.json" ]; then
    echo "(Re)starting $SERVICE_NAME now..."
    launchctl kickstart -k system/$SERVICE_NAME || true
fi

echo "$SERVICE_NAME has been installed"
echo "Thank you for installing nodex-agent!"

exit 0
