[package]
authors = ["NodeX Authors <>"]
categories = ["cryptography", "embedded"]
description = "Automate device security provisioning with edge intelligence."
edition = "2018"
keywords = ["did", "embedded", "iot", "root-of-trust"]
license-file = "LICENSE"
name = "nodex"
readme = "README.md"
version = "1.2.4"

documentation = "https://docs.nodecross.io"
homepage = "https://nodecross.io"
repository = "https://github.com/nodecross/nodex"

build = "build.rs"

[workspace]
members = ["e2e"]

[[bin]]
name = "nodex-agent"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
alloc = []
default = ["std"]
std = []

[dependencies]
actix-rt = { version = "2.9.0" }
actix-web = { version = "4.5.1" }
anyhow = "1.0.81"
async-trait = { version = "0.1.79" }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5.4", features = ["cargo", "derive"] }
cuid = { version = "1.3.2" }
dirs = { version = "5.0.1" }
dotenvy = "0.15.7"
env_logger = { version = "0.11.3", features = ["color"] }
hex = { version = "0.4.3" }
hmac = { version = "0.12.1" }
home-config = { version = "0.6.0", features = ["json", "toml", "yaml"] }
libloading = { version = "0.8.3" }
log = { version = "0.4.21" }
mac_address = "1.1.5"
nodex-didcomm = { git = "https://github.com/nodecross/nodex-didcomm", tag = "0.1.0" }
reqwest = { version = "0.11", features = [
    "json",
    "rustls-tls",
], default-features = false }
rumqttc = { version = "0.24.0" }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.115" }
sha2 = { version = "0.10.8" }
shadow-rs = "0.27.1"
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["full"] }
uuid = { version = "1.8.0", features = [
    "fast-rng",
    "macro-diagnostics",
    "serde",
    "v4",
] }
zip-extract = "0.1.3"

[dev-dependencies]
nodex-didcomm = { git = "https://github.com/nodecross/nodex-didcomm", tag = "0.1.0" }
rstest = { version = "0.18.2" }

[build-dependencies]
shadow-rs = "0.27.1"

[profile.dev]
debug = true
panic = "abort"

[profile.test]
debug = true
opt-level = 3
panic = "abort"

[profile.release]
panic = "abort"
strip = true
