FROM debian:bullseye

RUN apt-get update \
    && apt-get install -y ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
COPY ./fixtures/client-cert.crt /usr/local/share/ca-certificates/

RUN update-ca-certificates
