name: e2e test
description: ""
inputs:
  binary-path:
    required: true
    description: ""
  github-token:
    required: true
    description: ""
runs:
  using: composite
  steps:
    - name: (setup) copy default config to home
      shell: bash
      run: mkdir -p ~/.config/nodex & cp test_resource/config/* ~/.config/nodex/

    - name: (run) run mock server
      shell: bash
      run: docker compose -f test_resource/compose.yaml up -d --wait

    - name: (run) show docker image status
      shell: bash
      run: docker compose -f test_resource/compose.yaml ps

    - name: (run) run agent for e2e tests
      shell: bash
      run: ${{ inputs.binary-path }} > log.txt 2>&1 &
      env:
        NODEX_DID_HTTP_ENDPOINT: http://localhost:4010
        NODEX_DID_ATTACHMENT_LINK: http://localhost:4010
        NODEX_HUB_HTTP_ENDPOINT: http://localhost:8020
        RUST_BACKTRACE: 1

    - name: (run) e2e tests
      shell: bash
      working-directory: e2e
      run: cargo test

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ always() }}

    - name: (run) show log of agent
      shell: bash
      run: cat log.txt
      if: ${{ always() }}

    - name: (run) show log of mock server
      shell: bash
      run: docker compose -f test_resource/compose.yaml logs
      if: ${{ always() }}
